### ISSUE TITLE
Friendship not reflected on both users

### ISSUE THREAD

**Issue by rvvergara** [JamesOkunlade/facelook#3]
Added user does not reflect the adder as a friend:

1. Creating two users `ryto` and `mike`
2. Running `ryto.friendships.create(added_id: mike.id)` is successful
3. Running `ryto.friends` results in:
![image](https://user-images.githubusercontent.com/6015315/57962980-8c516580-7950-11e9-9fe9-3cd8b07bb9b5.png)

4. Running `mike.friends`, however, results in an empty array:

![image](https://user-images.githubusercontent.com/6015315/57962983-9ecb9f00-7950-11e9-80f9-31f6a68e0058.png)

The reason for this is that in the `user` model, only one side of this friendship is included as an association:

![image](https://user-images.githubusercontent.com/6015315/57963009-d20e2e00-7950-11e9-9727-05a92f21edf0.png)

The other side should also be included as an association.

**Comment by JamesOkunlade** [comment]
Hello @rvvergara , 

Please kindly review it again as this is no longer an issue. 

![image](https://user-images.githubusercontent.com/26285695/58825901-5510d300-8637-11e9-97d6-6cbdb923e907.png)

Friendship is always established for both the adder and the added. 

And as for converting the test to Rspec, we'd appreciate if you can review the controllers and view as well so we can submit it back together for re-review.

**Comment by rvvergara** [comment]
Sadly :( This issue still persists.

Let me write again the steps to recreate:
![image](https://user-images.githubusercontent.com/6015315/58929737-f9eff500-878a-11e9-9505-06b2ebe6c07a.png)

To clarify, here is what I wanted to do -> `ryto` creates a friendship with `mike` (`ryto.friendships.create(added_id: mike.id)`). Then after this i'd like to see `ryto` as one of `mike` 's friends: `mike.friends`.. But this returns an empty array.

**Comment by JamesOkunlade** [comment]
Issue 3 

![image](https://user-images.githubusercontent.com/26285695/61537626-80a51c80-aa2f-11e9-9748-37dbe71a0b31.png)

We have fixed other comments.
